### ISSUE TITLE
LED controll?

### ISSUE THREAD

**Issue by TheWeirdDodo** [BenRoe/Plaid-Pad#3]
Hi there,
I just wand to know if there is any way to controll the red and green LED during opperation of the macropad. This could be usefull to identify what macro layer is active.

**Comment by BenRoe** [comment]
Check the Plaid [keymap code](https://github.com/qmk/qmk_firmware/blob/63cb273d1504d070ce7ea6e84f86e22b1d665206/keyboards/dm9records/plaid/keymaps/default/keymap.c#L215). It's very similar for the Plaid-Pad Rev1 & Rev2.
The LED on the Rev3 is "only" a power indicator.
