### ISSUE TITLE
Add Links to the Rev 3 Source Code

### ISSUE THREAD

**Issue by alphonus** [BenRoe/Plaid-Pad#5]
The code for the Rev 2 and 1 is hidden in a link. But for the rev 3 I could only find the compiled file. I want to change what is displayed on the oled and am a newbee when it comes to qmk

**Comment by BenRoe** [comment]
If you wanna change the VIAL firmware, then you can find the line of code [here](https://github.com/vial-kb/vial-qmk/blob/a977deb2b55118436dca6c625cac5916cbb23f93/keyboards/keycapsss/plaid_pad/keymaps/vial/keymap.c#L66)(VIAL repo).

In the [QMK repo](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keycapsss/plaid_pad/keymaps/oled) you can find a keymap which shows the current layer (no VIAL support).
